#!/usr/bin/env python3
"""
Populate the Honey Index (D1) from stamped JSONL files.

Run on swarmrails, outputs SQL inserts that can be piped to wrangler d1.
Or uses the D1 HTTP API directly.

Usage:
    # Generate SQL file
    python3 scripts/populate_index.py \
        --input /data2/hive_audit/cre_honey_stamped.jsonl \
        --bucket sb-cre-verified \
        --r2-key master/cre_honey_stamped.jsonl \
        --output inserts.sql

    # Then apply:
    wrangler d1 execute honey-db --file=inserts.sql

    # Or use D1 API directly:
    python3 scripts/populate_index.py \
        --input /data2/hive_audit/cre_honey_stamped.jsonl \
        --bucket sb-cre-verified \
        --r2-key master/cre_honey_stamped.jsonl \
        --d1-api --account-id YOUR_ID --database-id YOUR_DB_ID --api-token YOUR_TOKEN

Swarm & Bee LLC — 2026
"""

import json
import argparse
import sys
import hashlib
from pathlib import Path

# Map legacy tier names to RJP-1 canonical tiers
TIER_MAP = {
    'genesis': 'royal_jelly',
    'royal_jelly': 'royal_jelly',
    'honey': 'honey',
    'cluster': 'pollen',
    'pollen': 'pollen',
    'cell': 'propolis',
    'propolis': 'propolis',
    'swarm': 'propolis',
}

def score_to_tier(score):
    """RJP-1 tier thresholds."""
    if score >= 95: return 'royal_jelly'
    if score >= 85: return 'honey'
    if score >= 70: return 'pollen'
    return 'propolis'

def extract_preview(record, max_len=200):
    """Extract a short preview of the user message for catalog display."""
    messages = record.get('messages', record.get('conversations', []))
    for msg in messages:
        if msg.get('role') == 'user':
            content = msg.get('content', '')[:max_len]
            return content.replace("'", "''").replace('\n', ' ')
    return ''

def content_hash(record):
    """Generate fingerprint if not present. Uses SHA256 per RJP-1 standard."""
    messages = record.get('messages', record.get('conversations', []))
    parts = []
    for msg in messages:
        role = msg.get('role', '').strip().lower()
        content = msg.get('content', '').strip().lower()
        parts.append(f"{role}:{content}")
    blob = "|".join(sorted(parts))
    return hashlib.sha256(blob.encode('utf-8')).hexdigest()


def generate_sql(input_path, bucket, r2_key, output_path, batch_size=500):
    """Generate SQL INSERT statements from stamped JSONL."""
    
    print(f"Reading: {input_path}")
    records = []
    with open(input_path, 'r') as f:
        for line_num, line in enumerate(f):
            line = line.strip()
            if not line:
                continue
            try:
                record = json.loads(line)
                records.append((line_num, record))
            except json.JSONDecodeError:
                print(f"  WARN: skipped malformed line {line_num}")
                continue

    print(f"  Loaded {len(records)} records")

    with open(output_path, 'w') as out:
        out.write("-- Hive Warehouse Index Population\n")
        out.write(f"-- Source: {input_path}\n")
        out.write(f"-- Records: {len(records)}\n")
        out.write(f"-- Generated by populate_index.py\n\n")
        out.write("BEGIN TRANSACTION;\n\n")

        for i, (line_num, record) in enumerate(records):
            cell_id = record.get('cell_id', f"cell_{line_num}")
            fingerprint = record.get('fingerprint', content_hash(record))
            task_type = record.get('task_type', 'unclassified')
            # Support both flat format and HiveCell (jelly_score.score / grade)
            js = record.get('jelly_score', {})
            score = js.get('score', 0) if js else 0
            if not score:
                score = record.get('verification_score', record.get('score', record.get('gate_score', 50)))
            tier = record.get('grade', record.get('tier', record.get('cook_tier', score_to_tier(score))))
            tier = TIER_MAP.get(tier, tier)  # Normalize legacy tier names
            domain = record.get('domain', 'cre')
            cluster = record.get('cluster', '')
            preview = extract_preview(record)

            # Escape single quotes for SQL
            cell_id = cell_id.replace("'", "''")
            task_type = task_type.replace("'", "''")
            cluster = cluster.replace("'", "''") if cluster else ''

            out.write(
                f"INSERT OR IGNORE INTO cells "
                f"(cell_id, fingerprint, task_type, tier, score, domain, cluster, "
                f"r2_bucket, r2_key, line_number, message_preview) VALUES ("
                f"'{cell_id}', '{fingerprint}', '{task_type}', '{tier}', {score}, "
                f"'{domain}', '{cluster}', '{bucket}', '{r2_key}', {line_num}, "
                f"'{preview[:200]}');\n"
            )

            if (i + 1) % batch_size == 0:
                out.write(f"\n-- Batch {(i+1) // batch_size} ({i+1} records)\n")

        out.write("\nCOMMIT;\n")
        out.write(f"\n-- Total: {len(records)} records\n")
        out.write("-- Verify: SELECT COUNT(*) FROM cells;\n")

    print(f"  SQL written to: {output_path}")
    print(f"  Apply with: wrangler d1 execute honey-db --file={output_path}")


def generate_honeycard_sql(honeycards_dir, output_path):
    """Generate SQL for HoneyCard inserts."""
    cards_dir = Path(honeycards_dir)
    cards = list(cards_dir.glob("*_HONEYCARD.json")) + list(cards_dir.glob("MASTER_HONEYCARD*.json"))
    
    print(f"Found {len(cards)} HoneyCards in {honeycards_dir}")

    with open(output_path, 'w') as out:
        out.write("-- HoneyCard Index Population\n\n")
        
        for card_path in cards:
            with open(card_path) as f:
                card = json.load(f)
            
            card_id = card_path.stem
            task_type = card.get('task_type', card.get('asset_name', card_id))
            domain = card.get('domain', 'cre')
            cell_count = card.get('cell_count', 0)
            avg_score = card.get('verification_score', card.get('avg_score', 0))
            tier_dist = json.dumps(card.get('grade_distribution', {}))
            card_json = json.dumps(card).replace("'", "''")

            out.write(
                f"INSERT OR REPLACE INTO honeycards "
                f"(card_id, task_type, domain, card_json, cell_count, avg_score, tier_distribution) VALUES ("
                f"'{card_id}', '{task_type}', '{domain}', '{card_json}', {cell_count}, {avg_score}, '{tier_dist}');\n"
            )

    print(f"  HoneyCard SQL written to: {output_path}")


def main():
    parser = argparse.ArgumentParser(description='Populate Honey Index from stamped JSONL')
    parser.add_argument('--input', required=True, help='Path to stamped JSONL file')
    parser.add_argument('--bucket', required=True, help='R2 bucket name (e.g., sb-cre-verified)')
    parser.add_argument('--r2-key', required=True, help='R2 object key (e.g., master/cre_honey_stamped.jsonl)')
    parser.add_argument('--output', default='inserts.sql', help='Output SQL file')
    parser.add_argument('--honeycards', help='Path to honeycards directory (optional)')
    parser.add_argument('--honeycards-output', default='honeycards_inserts.sql', help='HoneyCard SQL output')
    
    args = parser.parse_args()

    if not Path(args.input).exists():
        print(f"ERROR: Input file not found: {args.input}")
        sys.exit(1)

    generate_sql(args.input, args.bucket, args.r2_key, args.output)

    if args.honeycards and Path(args.honeycards).is_dir():
        generate_honeycard_sql(args.honeycards, args.honeycards_output)

    print("\nDone. Next steps:")
    print(f"  1. wrangler d1 execute honey-db --file={args.output}")
    if args.honeycards:
        print(f"  2. wrangler d1 execute honey-db --file={args.honeycards_output}")
    print("  3. Verify: wrangler d1 execute honey-db --command='SELECT COUNT(*) FROM cells'")


if __name__ == '__main__':
    main()
